apiVersion: v1
kind: Service
metadata:
  name: nfa-proxy-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  selector:
    app: nfa-proxy
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
