apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  ports:
    - name: main
      port: 3334
      targetPort: 3334
      protocol: TCP
    - name: health
      port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: consumer
