apiVersion: v1
kind: Service
metadata:
  name: provider-service
spec:
  type: LoadBalancer
  selector:
    app: provider
  ports:
    - name: api
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: proxy
      protocol: TCP
      port: 3333
      targetPort: 3333